name: CI

on:
  push:
    branches:
      - main
      - feature/initial-scaffold
  pull_request:
    branches:
      - main

jobs:
  URL-shortener-test-cases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Run tests
        run: |
          PYTHONPATH=".:backend" pytest -q backend